name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pacman
        uses: abozanona/pacman-contribution-graph@v1
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move to folder
        run: |
          mkdir -p pacman-contrib
          mv pacman-contribution-graph.svg pacman-contrib/

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add pacman-contrib/
          git commit -m "Update Pacman contribution graph" || exit 0
          git push
